<?php

namespace Lmi\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Lmi\EventBundle\Constants\Constants;

/**
 * SoireeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class AbstractRepository extends EntityRepository
{
	/**
	 * Build a paginator.
	 * @param unknown $query
	 * @param unknown $page
	 * @param unknown $nbElmtByPage
	 */
	protected function buildPaginator($query, $page, $nbElmtByPage)
	{
		$query->setFirstResult(($page-1) * $nbElmtByPage)
			  ->setMaxResults($nbElmtByPage);
		
		return new Paginator($query);
	}
	
}
