<?php

namespace Lmi\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarInfosRepository extends EntityRepository
{
}
