<?php

namespace Lmi\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Lmi\EventBundle\Constants\Constants;

/**
 * DanceSchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanceSchoolRepository extends AbstractRepository
{
	/**
	 * Find all published dance school
	 * @param $page
	 * @param $nbDanceSchoolByPage
	 */
	public function findAllDanceSchools($page, $nbDanceSchoolByPage) {
		$qb = $this->createQueryBuilder('d');
	
		$qb->where($qb->expr()->eq('d.publication', ':published'))
		   ->setParameter(':published', true);
	
		return $this->buildPaginator($qb->getQuery(), $page, $nbDanceSchoolByPage);
	}
}
