<?php

namespace Lmi\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Lmi\EventBundle\Constants\ConstParamAttributs;

/**
 * PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends EntityRepository
{
	/**
	 * Find next published events dates with limit
	 * @param integer $limit
	 */
	public function findDates($limit)
	{
		$nq = $this->createNativeNamedQuery('pventsDates')
		->setParameter(ConstParamAttributs::PARAM_SQL_PUBLISHED, true)
		->setParameter(ConstParamAttributs::PARAM_SQL_LIMIT, $limit);
	
		return $nq->getResult();
	}
}
